site_name: Pixel Composer Documentation

theme:
    name: null
    custom_dir: 'theme\'

nav:
  - "index.md"
  - "ui.md"
  - "node.md"
  - 'Node reference':
    - 'Node_ref/Import-Export Image(s).md'
    - 'Node_ref/Working with spritesheet.md'
    - 'Node_ref/Distortion.md'
    - 'Node_ref/Coloring.md'
    - 'Node_ref/Particle.md'
    - 'Node_ref/3D.md'